### ISSUE TITLE
Example pages from Figma

### ISSUE THREAD

**Issue by sitenativedev** [Telegram-Mini-Apps/TelegramUI#11]
It would be a good idea to make examples of applications that are in Figma:

<img width="380" alt="image" src="https://github.com/XeleneStudio/TelegramUI/assets/87825983/69bf14f0-a77a-478f-bf7a-cccc62038212">

I tried to do this, but there are problems with importing many components (cell, tabs list, select control and other).
This library is not ready for production.

**Comment by mainsmirnov** [comment]
Hi, can you share details of your problems with components?

**Comment by mainsmirnov** [comment]
We have example here https://github.com/XeleneStudio/TGUI-Example

**Comment by mainsmirnov** [comment]
Hey, we didn't get any response back. If you have any further questions after reviewing the repository, feel free to reopen the issue
