### ISSUE TITLE
How to import ButtonCell, Info, Navigation?

### ISSUE THREAD

**Issue by bshelkhonov** [Telegram-Mini-Apps/TelegramUI#14]
Hello, I'm struggling to import ButtonCell and other components from Cell. 

```Typescript
import { ButtonCell } from "@xelene/tgui"; // doesn't work
```

I think they should be imported in this file https://github.com/XeleneStudio/TelegramUI/blob/main/src/components/Blocks/index.ts

**Comment by mainsmirnov** [comment]
Thank you for issue, fixed in version 2.1.1 https://github.com/Telegram-Mini-Apps/TelegramUI/commit/61b1e04101ae8c727d3092379e255b4d3497084a
