### ISSUE TITLE
Cell UI Bug

### ISSUE THREAD

**Issue by wishyoudie** [Telegram-Mini-Apps/TelegramUI#27]
Single-cell sections have a hover bug, where it displays as last child.

Normal state:
<img width="367" alt="image" src="https://github.com/Telegram-Mini-Apps/TelegramUI/assets/66038379/37df0ae9-b853-4c08-8880-636110d50a8e">

Hover state:
<img width="397" alt="image" src="https://github.com/Telegram-Mini-Apps/TelegramUI/assets/66038379/506d3763-be00-4db0-b444-608f20db08a2">

Code used:
```
<List>
      <Section header="Recent Transactions">
        <Cell>asd</Cell>
      </Section>
</List>
```

**Comment by uicodee** [comment]
I have same issue
