### ISSUE TITLE
Custom colors usage

### ISSUE THREAD

**Issue by Kononenko-Daniil** [Telegram-Mini-Apps/TelegramUI#30]
I'm developing a mini-app using the TelegramUI library. And I had the following problem:
I need to make some elements like Button and Badge in a different color (like green). And I don't understand how to do this. I tried changing the variable values ​​directly in my `global.css` file (for example, `--tgui--button_color: green;`), but nothing changes.

Tell me, is it possible to somehow change the colors of the elements to custom ones?

I am developing Next.JS application. I am also using Tailwind.

**Comment by bshelkhonov** [comment]
Hello. Marking values as !important helped me

**Comment by Kononenko-Daniil** [comment]
@bshelkhonov Thank you very much! This really helped) I'm closing the issue

**Comment by kesha-antonov** [comment]
```
* {
  --tgui--font-family: 'Inter', sans-serif;
}
```

Also works

**Comment by kesha-antonov** [comment]
Found better way:

`styles.module.css`:
```
.test {
  --tgui--font-family: 'Inter', sans-serif;
}
```

```
import styles1 from './styles.module.css'

...

      <AppRoot
        appearance='light'
        className={styles1.test}
      >
```
