### ISSUE TITLE
Cell component remains on hover in ios

### ISSUE THREAD

**Issue by mourraille** [Telegram-Mini-Apps/TelegramUI#52]
When I interact with a <Cell> component it remains 'hovered' after the action is performed. It seems not to be the case when it renders on the desktop telegram version. Is it something to do with Tappable ?

**Comment by mainsmirnov** [comment]
Hi, what version of the library are you using?

**Comment by mourraille** [comment]
Hi @mainsmirnov , 

I'm on `@telegram-apps/telegram-ui": ^2.1.4` 

In this example, you can see when there's a tap on the Cell it remains focused. I have to click outside somewhere else in the app layout for it to come back to the normal state. 

https://github.com/user-attachments/assets/42c3b9f1-4a5d-4923-8ee1-e2664117d7dd

**Comment by mainsmirnov** [comment]
The issue has already been fixed in version 2.1.7. Please consider using the latest version :)

https://github.com/Telegram-Mini-Apps/TelegramUI/pull/45

**Comment by mourraille** [comment]
https://github.com/Telegram-Mini-Apps/TelegramUI/pull/45

😞 I missed it, thanks a lot.

**Comment by S1lentium** [comment]
Now there is a problem with the priority of the :active selector and :hover. :active selector is overridden with :hover
