### ISSUE TITLE
Section component uses incorrect color variable

### ISSUE THREAD

**Issue by zhelezkov** [Telegram-Mini-Apps/TelegramUI#59]
Hey!
I noticed that `Section` component uses `--tgui--bg_color`, but in my understanding it should use `--tgui--section_bg_color` variable. otherwise there's some inconsistency comparing to tg theme
https://github.com/Telegram-Mini-Apps/TelegramUI/blob/main/src/components/Blocks/Section/Section.module.css#L3

**Comment by wishyoudie** [comment]
Fixed in #53. Waiting for maintainers to approve.

**Comment by zhelezkov** [comment]
amazing! thanks a lot for a quick response
