### ISSUE TITLE
Cant import ModalHeader

### ISSUE THREAD

**Issue by mourraille** [Telegram-Mini-Apps/TelegramUI#63]
is this component supported yet? I can't manage to import it on 2.1.7

`export 'ModalHeader' (imported as 'ModalHeader') was not found in '@telegram-apps/telegram-ui' (possible exports: Accordion, AppRoot, Avatar, AvatarStack, Badge, Banner, Blockquote, Breadcrumbs, Button, ButtonCell, Caption, Card, Cell, Checkbox, Chip, CircularProgress, ColorInput, CompactPagination, Divider, FileInput, FixedLayout, Headline, IconButton, IconContainer, Image, Info, InlineButtons, Input, LargeTitle, Link, List, Modal, Multiselect, Multiselectable, Navigation, Pagination, PinInput, Placeholder, Popper, Progress, Radio, Rating, RootRenderer, Section, SegmentedControl, Select, Selectable, Skeleton, Slider, Snackbar, Spinner, Spoiler, Steps, Subheadline, Switch, Tabbar, TabsList, Tappable, Text, Textarea, Timeline, Title, Tooltip, Typography, VisuallyHidden)`

```

      <Modal
        style={{
          backgroundColor: "var(--tg-theme-secondary-bg-color)",
          borderRadius: "10px 10px 0 0",
        }}
        header={<ModalHeader>Only iOS header</ModalHeader>}
        trigger={
          <Button mode='bezeled' size='m' after={<UilEye size={18} />}>
            Preview page
          </Button>
        }
      >
```

**Comment by mainsmirnov** [comment]
Hey, thank you for your issue, you should utilize it with `Modal.Header`, not `ModalHeader`
