### ISSUE TITLE
Use the Popper component without an arrow

### ISSUE THREAD

**Issue by erickskrauch** [Telegram-Mini-Apps/TelegramUI#67]
How can I do that? Our design requires no arrow. But I can't remove the arrow in any way :(

**Comment by mainsmirnov** [comment]
Hi, you can pass empty component as an arrow.

```
const EmptyArrow = () => null;
return (
    <Popper targetRef={ref} ArrowIcon={EmptyArrow}>
      <Caption level="1">Hello</Caption>
    </Popper>
);
```

**Comment by erickskrauch** [comment]
Nice solution :+1:  But I would suggest just allowing passing `null` to archive the same behavior.

**Comment by erickskrauch** [comment]
There is an option `withArrow` :man_facepalming: 
```
<Popper withArrow={false} />
```
